# Generated by Django 3.2.12 on 2022-02-17 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pray_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('Adhola_Prayer', models.TextField()),
                ('Book', models.CharField(max_length=45)),
                ('img', models.ImageField(upload_to='pic')),
                ('Posted_by', models.CharField(max_length=45)),
                ('English_Prayer', models.TextField()),
                ('daily_prayer_detail', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
    ]
